modLoader = "javafml" #mandatory
loaderVersion = "*" #mandatory. Allow all forge versions
license = "${license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
logoFile = "assets/${mod_id}/icon.png" #optional
credits = "${credits}"
authors = $mod_authors
description = "A native in-game music client for Minecraft with YouTube and local file playback."

[[dependencies.${mod_id}]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[0,)" #mandatory
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_forgemc_versions}"
ordering = "NONE"
side = "CLIENT"
