# The current version of Minecraft the project will use
mc_ver=26.1.2

# Mod Info
mod_name=XMusic
mod_authors=["CodeXceed"]
mod_id=xmusic
mod_version=1.0.0
group=com.codexceed.xmusic
license=MIT
credits=Built with Unimined
description=A fully integrated in-game music and media system for Minecraft

# Manifold
manifold_version=2026.1.7

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.caching=true
#org.gradle.configuration-cache=true
org.gradle.java.installations.auto-download=true
