# General Properties
java_version=25
minecraft_version=26.1.2
compatible_mc_versions=["26.1", "26.1.1", "26.1.2"]

# Fabric-specific Properties
fabric_loader=0.19.2
fabric_api_version=0.149.1+26.1.2

# Selected loaders
builds_for=fabric
